<?php

use Illuminate\Database\Seeder;

class ClientesMonitoramentoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clientes_monitoramento')->insert([

            ['mcu_cliente' => '6765','codigo' => '9100','cliente' => 'AC COIMBRA - GO'],
            ['mcu_cliente' => '6664','codigo' => '9101','cliente' => 'AC RIO VERDE - GO'],
            ['mcu_cliente' => '54341','codigo' => '9104','cliente' => 'AC GARAVELO - GO'],
            ['mcu_cliente' => '59055','codigo' => '9105','cliente' => 'AC GOIÁ - GO'],
            ['mcu_cliente' => '59183','codigo' => '9106','cliente' => 'AC NOVA SUÍÇA - GO'],
            ['mcu_cliente' => '58751','codigo' => '9107','cliente' => 'AC PALMITO - GO'],
            ['mcu_cliente' => '59056','codigo' => '9109','cliente' => 'AC PARQUE ATENEU - GO'],
            ['mcu_cliente' => '54050','codigo' => '9110','cliente' => 'AC SÃO PATRÍCIO - GO'],
            ['mcu_cliente' => '6605','codigo' => '9112','cliente' => 'AC CENTRAL DE GOIANIA - GO'],
            ['mcu_cliente' => '6766','codigo' => '9114','cliente' => 'AC VILA NOVA - GO'],
            ['mcu_cliente' => '6848','codigo' => '9115','cliente' => 'AC ADELANDIA - GO'],
            ['mcu_cliente' => '6713','codigo' => '9116','cliente' => 'AC ÁGUA LIMPA - GO'],
            ['mcu_cliente' => '6822','codigo' => '9118','cliente' => 'AC AMERICANO DO BRASIL - GO'],
            ['mcu_cliente' => '6683','codigo' => '9119','cliente' => 'AC AMORINOPOLIS - GO'],
            ['mcu_cliente' => '6756','codigo' => '9120','cliente' => 'AC ARAÇÚ - GO'],
            ['mcu_cliente' => '6685','codigo' => '9121','cliente' => 'AC ARAGARCAS - GO'],
            ['mcu_cliente' => '6757','codigo' => '9122','cliente' => 'AC ARAGOIANIA - GO'],
            ['mcu_cliente' => '6786','codigo' => '9123','cliente' => 'AC ARAGUAPAZ - GO'],
            ['mcu_cliente' => '6687','codigo' => '9124','cliente' => 'AC AVELINOPOLIS - GO'],
            ['mcu_cliente' => '6688','codigo' => '9125','cliente' => 'AC BALIZA - GO'],
            ['mcu_cliente' => '55345','codigo' => '9126','cliente' => 'AC BERNARDO SAYÃO - GO'],
            ['mcu_cliente' => '6689','codigo' => '9127','cliente' => 'AC BOM JARDIM DE GOIAS - GO'],
            ['mcu_cliente' => '6690','codigo' => '9128','cliente' => 'AC BRITANIA - GO'],
            ['mcu_cliente' => '6929','codigo' => '9129','cliente' => 'AC BURITI DE GOIAS - GO'],
            ['mcu_cliente' => '6691','codigo' => '9130','cliente' => 'AC CACHOEIRA DE GOIAS - GO'],
            ['mcu_cliente' => '6770','codigo' => '9131','cliente' => 'AC CACHOEIRA DOURADA - GO'],
            ['mcu_cliente' => '6935','codigo' => '9132','cliente' => 'AC CALDAZINHA - GO'],
            ['mcu_cliente' => '6824','codigo' => '9133','cliente' => 'AC CAMPINAÇÚ - GO'],
            ['mcu_cliente' => '6619','codigo' => '9134','cliente' => 'AC CAMPINAS - GO'],
            ['mcu_cliente' => '54051','codigo' => '9135','cliente' => 'AC CAMPO LIMPO DE GOIAS - GO'],
            ['mcu_cliente' => '6856','codigo' => '9136','cliente' => 'AC CAMPOS VERDES - GO'],
            ['mcu_cliente' => '6819','codigo' => '9137','cliente' => 'AC CANAA - GO'],
            ['mcu_cliente' => '6937','codigo' => '9138','cliente' => 'AC CASTELANDIA - GO'],
            ['mcu_cliente' => '6760','codigo' => '9139','cliente' => 'AC CATURAI - GO'],
            ['mcu_cliente' => '6945','codigo' => '9140','cliente' => 'CDD AEROVIARIO - GO'],
            ['mcu_cliente' => '6944','codigo' => '9141','cliente' => 'CDD ANAPOLIS - GO'],
            ['mcu_cliente' => '6952','codigo' => '9142','cliente' => 'CDD BANDEIRAS - GO'],
            ['mcu_cliente' => '6943','codigo' => '9143','cliente' => 'CDD GOIANIA - GO'],
            ['mcu_cliente' => '57950','codigo' => '9144','cliente' => 'CDD GUANABARA - GO'],
            ['mcu_cliente' => '46557','codigo' => '9145','cliente' => 'CDD ITUMBIARA - GO'],
            ['mcu_cliente' => '6947','codigo' => '9146','cliente' => 'CDD JARDIM AMERICA - GO'],
            ['mcu_cliente' => '46553','codigo' => '9147','cliente' => 'CDD JATAI - GO'],
            ['mcu_cliente' => '6954','codigo' => '9148','cliente' => 'CDD JUSCELINO KUBSTICHEK - GO'],
            ['mcu_cliente' => '6956','codigo' => '9149','cliente' => 'CDD PADRE PELÁGIO - GO'],
            ['mcu_cliente' => '6946','codigo' => '9150','cliente' => 'CDD VILA NOVA - GO'],
            ['mcu_cliente' => '6709','codigo' => '9151','cliente' => 'AC CERES - GO'],
            ['mcu_cliente' => '6936','codigo' => '9152','cliente' => 'AC CHAPADÃO DO CÉU - GO'],
            ['mcu_cliente' => '6720','codigo' => '9153','cliente' => 'AC CROMINIA - GO'],
            ['mcu_cliente' => '6722','codigo' => '9154','cliente' => 'AC DAVINÓPOLIS - GO'],
            ['mcu_cliente' => '6694','codigo' => '9155','cliente' => 'AC DIORAMA - GO'],
            ['mcu_cliente' => '6825','codigo' => '9156','cliente' => 'AC DOVERLANDIA - GO'],
            ['mcu_cliente' => '6860','codigo' => '9157','cliente' => 'AC EDEALINA - GO'],
            ['mcu_cliente' => '6861','codigo' => '9158','cliente' => 'AC FAINA - GO'],
            ['mcu_cliente' => '6695','codigo' => '9159','cliente' => 'AC FAZENDA NOVA - GO'],
            ['mcu_cliente' => '46555','codigo' => '9160','cliente' => 'CDD TRINDADE - GO'],
            ['mcu_cliente' => '6762','codigo' => '9161','cliente' => 'AC GOIANÁPOLIS - GO'],
            ['mcu_cliente' => '6654','codigo' => '9162','cliente' => 'AC GOIANÉSIA - GO'],
            ['mcu_cliente' => '6635','codigo' => '9163','cliente' => 'AC GOIÁS - GO'],
            ['mcu_cliente' => '6863','codigo' => '9164','cliente' => 'AC GOUVELANDIA - GO'],
            ['mcu_cliente' => '6934','codigo' => '9165','cliente' => 'AC GUARAITA - GO'],
            ['mcu_cliente' => '6864','codigo' => '9166','cliente' => 'AC GUARINOS - GO'],
            ['mcu_cliente' => '6655','codigo' => '9167','cliente' => 'AC HEITORAI - GO'],
            ['mcu_cliente' => '6933','codigo' => '9168','cliente' => 'AC INACIOLANDIA - GO'],
            ['mcu_cliente' => '6637','codigo' => '9169','cliente' => 'AC INHUMAS - GO'],
            ['mcu_cliente' => '54045','codigo' => '9170','cliente' => 'AC IPIRANGA DE GOIAS - GO'],
            ['mcu_cliente' => '6812','codigo' => '9171','cliente' => 'AC ISRAELANDIA - GO'],
            ['mcu_cliente' => '6658','codigo' => '9172','cliente' => 'AC ITABERAI - GO'],
            ['mcu_cliente' => '6835','codigo' => '9173','cliente' => 'AC ITAGUARI - GO'],
            ['mcu_cliente' => '6669','codigo' => '9174','cliente' => 'AC ITUMBIARA - GO'],
            ['mcu_cliente' => '6698','codigo' => '9175','cliente' => 'AC IVOLÂNDIA - GO'],
            ['mcu_cliente' => '6641','codigo' => '9177','cliente' => 'AC JATAI - GO'],
            ['mcu_cliente' => '6700','codigo' => '9178','cliente' => 'AC JAUPACI - GO'],
            ['mcu_cliente' => '54340','codigo' => '9179','cliente' => 'AC JAYARA - GO'],
            ['mcu_cliente' => '6938','codigo' => '9180','cliente' => 'AC JESUPOLIS - GO'],
            ['mcu_cliente' => '55329','codigo' => '9181','cliente' => 'AC LAGOA SANTA - GO'],
            ['mcu_cliente' => '6726','codigo' => '9182','cliente' => 'AC MAIRIPOTABA - GO'],
            ['mcu_cliente' => '6729','codigo' => '9183','cliente' => 'AC MARZAGÃO - GO'],
            ['mcu_cliente' => '6866','codigo' => '9184','cliente' => 'AC MATRINCHÃ - GO'],
            ['mcu_cliente' => '6748','codigo' => '9185','cliente' => 'AC MAURILANDIA - GO'],
            ['mcu_cliente' => '6702','codigo' => '9186','cliente' => 'AC MOIPORÁ - GO'],
            ['mcu_cliente' => '6703','codigo' => '9187','cliente' => 'AC MONTES CLAROS DE GOIAS - GO'],
            ['mcu_cliente' => '6928','codigo' => '9188','cliente' => 'AC MONTIVIDIU DO NORTE - GO'],
            ['mcu_cliente' => '426685','codigo' => '9189','cliente' => 'CDD SENADOR CANEDO - GO'],
            ['mcu_cliente' => '6667','codigo' => '9190','cliente' => 'AC MUTUNOPOLIS - GO'],
            ['mcu_cliente' => '6668','codigo' => '9191','cliente' => 'AC NIQUELANDIA - GO'],
            ['mcu_cliente' => '6670','codigo' => '9192','cliente' => 'AC NOVA AMÉRICA - GO'],
            ['mcu_cliente' => '53517','codigo' => '9194','cliente' => 'OFICINA DA GEREN - GO'],
            ['mcu_cliente' => '6871','codigo' => '9195','cliente' => 'AC PALESTINA DE GOIAS - GO'],
            ['mcu_cliente' => '6708','codigo' => '9196','cliente' => 'AC PALMEIRAS DE GOIAS - GO'],
            ['mcu_cliente' => '6733','codigo' => '9197','cliente' => 'AC PALMELO - GO'],
            ['mcu_cliente' => '6815','codigo' => '9198','cliente' => 'AC PALMINOPOLIS - GO'],
            ['mcu_cliente' => '6734','codigo' => '9199','cliente' => 'AC PANAMÁ - GO'],
            ['mcu_cliente' => '6764','codigo' => '9200','cliente' => 'AC PEDRO LUDOVICO - GO'],
            ['mcu_cliente' => '6672','codigo' => '9201','cliente' => 'AC PILAR DE GOIAS - GO'],
            ['mcu_cliente' => '6632','codigo' => '9202','cliente' => 'AC PORANGATU - GO'],
            ['mcu_cliente' => '6752','codigo' => '9203','cliente' => 'AC PORTELANDIA - GO'],
            ['mcu_cliente' => '52866','codigo' => '9204','cliente' => 'AC POUSADA DO RIO QUENTE - GO'],
            ['mcu_cliente' => '6940','codigo' => '9205','cliente' => 'AC PROFESSOR JAMIL - GO'],
            ['mcu_cliente' => '6563','codigo' => '9206','cliente' => 'AC RIO VERDE - ADMINISTRATIVO - GO'],
            ['mcu_cliente' => '6737','codigo' => '9207','cliente' => 'AC SANTA CRUZ DE GOIAS - GO'],
            ['mcu_cliente' => '6727','codigo' => '9208','cliente' => 'AC SANTA HELENA DE GOIAS - GO'],
            ['mcu_cliente' => '6829','codigo' => '9209','cliente' => 'AC SANTA ISABEL - GO'],
            ['mcu_cliente' => '6813','codigo' => '9210','cliente' => 'AC SANTA RITA DO ARAGUAIA - GO'],
            ['mcu_cliente' => '55333','codigo' => '9211','cliente' => 'AC SANTA RITA DO NOVO DESTINO - GO'],
            ['mcu_cliente' => '6779','codigo' => '9212','cliente' => 'AC SANTA ROSA DE GOIAS - GO'],
            ['mcu_cliente' => '6677','codigo' => '9213','cliente' => 'AC SANTA TEREZA DE GOIAS - GO'],
            ['mcu_cliente' => '6678','codigo' => '9214','cliente' => 'AC SANTA TEREZINHA DE GOIAS - GO'],
            ['mcu_cliente' => '6885','codigo' => '9215','cliente' => 'AC SANTO ANTONIO DE GOIAS - GO'],
            ['mcu_cliente' => '6880','codigo' => '9216','cliente' => 'AC SÃO LUIZ DO NORTE - GO'],
            ['mcu_cliente' => '6728','codigo' => '9217','cliente' => 'AC SÃO LUIZ DE MONTES BELOS - GO'],
            ['mcu_cliente' => '6881','codigo' => '9218','cliente' => 'AC SÃO MIGUEL DO PASSA QUATRO - GO'],
            ['mcu_cliente' => '6679','codigo' => '9219','cliente' => 'AC TAQUARAL DE GOIAS - GO'],
            ['mcu_cliente' => '6931','codigo' => '9220','cliente' => 'AC TEREZOPOLIS DE GOIAS - GO'],
            ['mcu_cliente' => '6738','codigo' => '9221','cliente' => 'AC TRES RANCHOS - GO'],
            ['mcu_cliente' => '6834','codigo' => '9222','cliente' => 'AC TROMBAS - GO'],
            ['mcu_cliente' => '6932','codigo' => '9224','cliente' => 'AC UIRAPURU - GO'],
            ['mcu_cliente' => '55339','codigo' => '9225','cliente' => 'AC URIAS MAGALHÂES - GO'],
            ['mcu_cliente' => '6671','codigo' => '9226','cliente' => 'AC URUAÇU - GO'],
            ['mcu_cliente' => '6781','codigo' => '9227','cliente' => 'AC VARJÃO - GO'],
            ['mcu_cliente' => '47867','codigo' => '9229','cliente' => 'AC VILA PROPICIO - GO'],
            ['mcu_cliente' => '60136','codigo' => '9352','cliente' => 'AC JARDIM DAS OLIVEIRAS - GO'],
            ['mcu_cliente' => '6769','codigo' => '9353','cliente' => 'AC HIDROLANDIA - GO'],
            ['mcu_cliente' => '6711','codigo' => '9355','cliente' => 'AC SANCLERLANDIA - GO'],
            ['mcu_cliente' => '6663','codigo' => '9356','cliente' => 'AC JARAGUÁ - GO'],
            ['mcu_cliente' => '6759','codigo' => '9357','cliente' => 'AC CAMPESTRE DE GOIAS - GO'],
            ['mcu_cliente' => '6776','codigo' => '9358','cliente' => 'AC SANTA BARBARA DE GOIAS - GO'],
            ['mcu_cliente' => '6684','codigo' => '9359','cliente' => 'AC ANICUNS - GO'],
            ['mcu_cliente' => '6696','codigo' => '9360','cliente' => 'AC FIRMINÓPOLIS - GO'],
            ['mcu_cliente' => '85748','codigo' => '9362','cliente' => 'AC 24 DE OUTUBRO - GO'],
            ['mcu_cliente' => '6758','codigo' => '9363','cliente' => 'AC BRAZABRANTES - GO'],
            ['mcu_cliente' => '6821','codigo' => '9364','cliente' => 'AC JARDIM AMERICA - GO'],
            ['mcu_cliente' => '6609','codigo' => '9365','cliente' => 'AC ANÁPOLIS - GO'],
            ['mcu_cliente' => '6682','codigo' => '9366','cliente' => 'AC TRINDADE - GO'],
            ['mcu_cliente' => '6827','codigo' => '9367','cliente' => 'AC INDIARA - GO'],
            ['mcu_cliente' => '6744','codigo' => '9368','cliente' => 'AC EDEIA - GO'],
            ['mcu_cliente' => '6736','codigo' => '9369','cliente' => 'AC PONTALINA - GO'],
            ['mcu_cliente' => '6723','codigo' => '9370','cliente' => 'AC GOIATUBA - GO'],
            ['mcu_cliente' => '6716','codigo' => '9371','cliente' => 'AC BURITI ALEGRE - GO'],
            ['mcu_cliente' => '6644','codigo' => '9372','cliente' => 'AC MORRINHOS - GO'],
            ['mcu_cliente' => '6693','codigo' => '9373','cliente' => 'AC QUIRINOPOLIS - GO'],
            ['mcu_cliente' => '6618','codigo' => '9374','cliente' => 'AC CALDAS NOVAS - GO'],
            ['mcu_cliente' => '6741','codigo' => '9376','cliente' => 'AC CACHOEIRA ALTA - GO'],
            ['mcu_cliente' => '6768','codigo' => '9377','cliente' => 'AC GUAPO - GO'],
            ['mcu_cliente' => '58754','codigo' => '9378','cliente' => 'AC SANTO ANTONIO DE RIO VERDE - GO'],
            ['mcu_cliente' => '6622','codigo' => '9380','cliente' => 'AC CATALÃO - GO'],
            ['mcu_cliente' => '6755','codigo' => '9381','cliente' => 'AC APARECIDA DE GOIANIA - GO'],
            ['mcu_cliente' => '46554','codigo' => '9382','cliente' => 'CDD CATALAO - GO'],
            ['mcu_cliente' => '60930','codigo' => '9384','cliente' => 'CDD LIBERDADE - GO'],
            ['mcu_cliente' => '6638','codigo' => '9385','cliente' => 'AC IPAMERI - GO'],
            ['mcu_cliente' => '46551','codigo' => '9386','cliente' => 'CDD CALDAS NOVAS - GO'],
            ['mcu_cliente' => '6883','codigo' => '9388','cliente' => 'AC SENADOR CANEDO - GO'],
            ['mcu_cliente' => '6950','codigo' => '9389','cliente' => 'CDD NOVO MUNDO - GO'],
            ['mcu_cliente' => '6615','codigo' => '9391','cliente' => 'AC BELA VISTA DE GOIAS - GO '],
            ['mcu_cliente' => '6782','codigo' => '9392','cliente' => 'AC VIANOPOLIS - GO'],
            ['mcu_cliente' => '6955','codigo' => '9393','cliente' => 'CDD OESTE MARISTA - GO'],
            ['mcu_cliente' => '59155','codigo' => '9394','cliente' => 'AC GALERIA AMERICA - GO'],
            ['mcu_cliente' => '6712','codigo' => '9395','cliente' => 'AC TURVANIA - GO'],
            ['mcu_cliente' => '6833','codigo' => '9396','cliente' => 'AC SÃO JOÃO DA PARAÚNA - GO'],
            ['mcu_cliente' => '6750','codigo' => '9397','cliente' => 'AC PARAUNA - GO'],
            ['mcu_cliente' => '6706','codigo' => '9398','cliente' => 'AC IPORÁ - GO'],
            ['mcu_cliente' => '6710','codigo' => '9399','cliente' => 'AC PIRANHAS - GO'],
            ['mcu_cliente' => '6560','codigo' => '9400','cliente' => 'REGIÃO DE ATENDIMENTO 04 - URUACU - GO'],
            ['mcu_cliente' => '60139','codigo' => '9401','cliente' => 'AC PLAZA D ORO SHOPPING - GO'],
            ['mcu_cliente' => '6743','codigo' => '9402','cliente' => 'AC CAIAPONIA - GO'],
            ['mcu_cliente' => '55343','codigo' => '9403','cliente' => 'AC VERA CRUZ - GO'],
            ['mcu_cliente' => '57147','codigo' => '9404','cliente' => 'AC PLANALTO - GO'],
            ['mcu_cliente' => '58749','codigo' => '9407','cliente' => 'AC DOIS IRMAOS - GO'],
            ['mcu_cliente' => '6671','codigo' => '9409','cliente' => 'UD URUACU - GO'],
            ['mcu_cliente' => '6847','codigo' => '9410','cliente' => 'AC ESMERALDA - GO'],
            ['mcu_cliente' => '425000','codigo' => '9411','cliente' => 'SALA-SEGURA CLI - GO'],
            ['mcu_cliente' => '6665','codigo' => '9412','cliente' => 'AC MARA ROSA - GO'],
            ['mcu_cliente' => '6747','codigo' => '9413','cliente' => 'AC JANDAIA - GO'],
            ['mcu_cliente' => '6653','codigo' => '9414','cliente' => 'AC FORMOSO - GO'],
            ['mcu_cliente' => '6680','codigo' => '9415','cliente' => 'AC MINAÇÚ - GO'],
            ['mcu_cliente' => '6778','codigo' => '9416','cliente' => 'AC SÃO MIGUEL DO ARAGUAIA - GO'],
            ['mcu_cliente' => '6650','codigo' => '9417','cliente' => 'AC CRIXÁS - GO'],
            ['mcu_cliente' => '6643','codigo' => '9419','cliente' => 'AC MINEIROS - GO'],
            ['mcu_cliente' => '6740','codigo' => '9420','cliente' => 'AC APORÉ - GO'],
            ['mcu_cliente' => '6742','codigo' => '9421','cliente' => 'AC CAÇU - GO'],
            ['mcu_cliente' => '6753','codigo' => '9422','cliente' => 'AC SÃO SIMÃO - GO'],
            ['mcu_cliente' => '62123','codigo' => '9423','cliente' => 'AC ALMERINDONOPOLIS - GO'],
            ['mcu_cliente' => '6724','codigo' => '9424','cliente' => 'AC BOM JESUS DE GOIAS - GO'],
            ['mcu_cliente' => '6751','codigo' => '9425','cliente' => 'AC ACREUNA - GO'],
            ['mcu_cliente' => '6735','codigo' => '9426','cliente' => 'AC PIRACANJUBA - GO'],
            ['mcu_cliente' => '6719','codigo' => '9427','cliente' => 'AC CRISTIANOPOLIS - GO'],
            ['mcu_cliente' => '6731','codigo' => '9428','cliente' => 'AC ORIZONA - GO'],
            ['mcu_cliente' => '6616','codigo' => '9429','cliente' => 'AC SILVÂNIA - GO'],
            ['mcu_cliente' => '6717','codigo' => '9430','cliente' => 'AC CAMPO ALEGRE DE GOIAS - GO'],
            ['mcu_cliente' => '59078','codigo' => '9431','cliente' => 'AC DOMICIANO RIBEIRO - GO'],
            ['mcu_cliente' => '6783','codigo' => '9432','cliente' => 'AC GOIANDIRA - GO'],
            ['mcu_cliente' => '6662','codigo' => '9433','cliente' => 'AC ITAUÇÚ - GO'],
            ['mcu_cliente' => '6661','codigo' => '9434','cliente' => 'AC ITAPURANGA - GO'],
            ['mcu_cliente' => '6868','codigo' => '9435','cliente' => 'AC MORRO AGUDO DE GOIAS - GO'],
            ['mcu_cliente' => '6697','codigo' => '9436','cliente' => 'AC ITAPIRAPUÃ - GO'],
            ['mcu_cliente' => '6701','codigo' => '9437','cliente' => 'AC JUSSARA - GO'],
            ['mcu_cliente' => '6701','codigo' => '9438','cliente' => 'UD JUSSARA - GO'],
            ['mcu_cliente' => '6715','codigo' => '9439','cliente' => 'AC ANHANGUERA - GO'],
            ['mcu_cliente' => '6646','codigo' => '9440','cliente' => 'AC BARRO ALTO - GO'],
            ['mcu_cliente' => '6926','codigo' => '9441','cliente' => 'AC ALTO HORIZONTE - GO'],
            ['mcu_cliente' => '423844','codigo' => '9444','cliente' => 'REGIÃO DE ATENDIMENTO 02 - GOIANIA SUL - GO'],
            ['mcu_cliente' => '6927','codigo' => '9445','cliente' => 'AC NOVA IGUACU DE GOIAS - GO'],
            ['mcu_cliente' => '6652','codigo' => '9446','cliente' => 'AC ESTRELA DO NORTE - GO'],
            ['mcu_cliente' => '58750','codigo' => '9447','cliente' => 'AC ITAGUAÇU - GO'],
            ['mcu_cliente' => '6870','codigo' => '9448','cliente' => 'AC NOVO PLANALTO - GO'],
            ['mcu_cliente' => '6660','codigo' => '9449','cliente' => 'AC ITAPACI - GO'],
            ['mcu_cliente' => '53038','codigo' => '9450','cliente' => 'AC AMARALINA - GO'],
            ['mcu_cliente' => '6780','codigo' => '9451','cliente' => 'AC SÃO FRANCISCO DE GOIÁS - GO'],
            ['mcu_cliente' => '6775','codigo' => '9452','cliente' => 'AC PETROLINA DE GOIAS - GO'],
            ['mcu_cliente' => '6674','codigo' => '9453','cliente' => 'AC RIANAPOLIS - GO'],
            ['mcu_cliente' => '6647','codigo' => '9454','cliente' => 'AC CAMPINORTE - GO'],
            ['mcu_cliente' => '6657','codigo' => '9455','cliente' => 'AC HIDROLINA - GO'],
            ['mcu_cliente' => '6673','codigo' => '9456','cliente' => 'AC RIALMA - GO'],
            ['mcu_cliente' => '6649','codigo' => '9457','cliente' => 'AC NOVA GLORIA - GO'],
            ['mcu_cliente' => '6656','codigo' => '9458','cliente' => 'AC PIRES DO RIO - GO'],
            ['mcu_cliente' => '6767','codigo' => '9459','cliente' => 'AC GOIANIRA - GO'],
            ['mcu_cliente' => '6681','codigo' => '9460','cliente' => 'AC URUANA- GO'],
            ['mcu_cliente' => '6739','codigo' => '9461','cliente' => 'AC URUTAI - GO'],
            ['mcu_cliente' => '6721','codigo' => '9462','cliente' => 'AC CUMARI - GO'],
            ['mcu_cliente' => '6732','codigo' => '9463','cliente' => 'AC OUVIDOR - GO'],
            ['mcu_cliente' => '6730','codigo' => '9464','cliente' => 'AC NOVA AURORA - GO'],
            ['mcu_cliente' => '6718','codigo' => '9465','cliente' => 'AC CORUMBAÍBA - GO'],
            ['mcu_cliente' => '47862','codigo' => '9467','cliente' => 'AC GAMELEIRA - GO'],
            ['mcu_cliente' => '6714','codigo' => '9468','cliente' => 'AC ALOANDIA - GO'],
            ['mcu_cliente' => '6725','codigo' => '9469','cliente' => 'AC JOVIANIA - GO'],
            ['mcu_cliente' => '6826','codigo' => '9470','cliente' => 'AC VICENTINOPOLIS - GO'],
            ['mcu_cliente' => '47863','codigo' => '9471','cliente' => 'AC PORTEIRAO - GO'],
            ['mcu_cliente' => '6884','codigo' => '9472','cliente' => 'AC TURVELANDIA - GO'],
            ['mcu_cliente' => '6930','codigo' => '9473','cliente' => 'AC SANTO ANTONIO DA BARRA - GO'],
            ['mcu_cliente' => '46560','codigo' => '9474','cliente' => 'CDD APARECIDA DE GOIANIA - GO '],
            ['mcu_cliente' => '6867','codigo' => '9475','cliente' => 'AC MONTIVIDIU - GO'],
            ['mcu_cliente' => '6745','codigo' => '9476','cliente' => 'AC ITAJÁ - GO'],
            ['mcu_cliente' => '61107','codigo' => '9477','cliente' => 'AC BRASIL PARK SHOPPING - GO'],
            ['mcu_cliente' => '6746','codigo' => '9479','cliente' => 'AC ITARUMA - GO '],
            ['mcu_cliente' => '61561','codigo' => '9480','cliente' => 'AC VILA MUTIRAO - GO'],
            ['mcu_cliente' => '6939','codigo' => '9481','cliente' => 'AC APARECIDA DO RIO DOCE - GO'],
            ['mcu_cliente' => '61115','codigo' => '9482','cliente' => 'AC MAYSA - GO'],
            ['mcu_cliente' => '6749','codigo' => '9484','cliente' => 'AC PARANAIGUARA - GO'],
            ['mcu_cliente' => '6949','codigo' => '9485','cliente' => 'CDD VILA COIMBRA - GO'],
            ['mcu_cliente' => '59771','codigo' => '9486','cliente' => 'CDD MARECHAL RONDON - GO'],
            ['mcu_cliente' => '61441','codigo' => '9487','cliente' => 'AC PARANAIBA SHOPPING - GO'],
            ['mcu_cliente' => '6659','codigo' => '9489','cliente' => 'AC ITAGUARU - GO'],
            ['mcu_cliente' => '6704','codigo' => '9490','cliente' => 'AC MOSSAMEDES - GO'],
            ['mcu_cliente' => '6772','codigo' => '9491','cliente' => 'AC NERÓPOLIS - GO'],
            ['mcu_cliente' => '6773','codigo' => '9492','cliente' => 'AC NOVA VENEZA - GO'],
            ['mcu_cliente' => '6774','codigo' => '9493','cliente' => 'AC OURO VERDE DE GOIAS - GO'],
            ['mcu_cliente' => '6728','codigo' => '9494','cliente' => 'UD SÃO LUÍS DE MONTES BELOS - GO'],
            ['mcu_cliente' => '6686','codigo' => '9495','cliente' => 'AC AURILANDIA - GO'],
            ['mcu_cliente' => '49587','codigo' => '9496','cliente' => 'AC ABADIA DE GOIAS - GO'],
            ['mcu_cliente' => '6692','codigo' => '9498','cliente' => 'AC CORREGO DO OURO - GO'],
            ['mcu_cliente' => '6707','codigo' => '9499','cliente' => 'AC NOVO BRASIL - GO '],
            ['mcu_cliente' => '6876','codigo' => '9500','cliente' => 'AC SANTA FÉ DE GOIAS - GO'],
            ['mcu_cliente' => '6853','codigo' => '9501','cliente' => 'AC BONFINOPOLIS - GO'],
            ['mcu_cliente' => '6705','codigo' => '9503','cliente' => 'AC NAZARIO - GO'],
            ['mcu_cliente' => '6648','codigo' => '9504','cliente' => 'AC CARMO DO RIO VERDE - GO'],
            ['mcu_cliente' => '6675','codigo' => '9505','cliente' => 'AC RUBIATABA - GO'],
            ['mcu_cliente' => '52872','codigo' => '9506','cliente' => 'AC FLAMBOYANT - GO'],
            ['mcu_cliente' => '52876','codigo' => '9507','cliente' => 'AC BURITI SHOPPING - GO'],
            ['mcu_cliente' => '58753','codigo' => '9508','cliente' => 'AC PORTAL SHOPPING - GO'],
            ['mcu_cliente' => '6666','codigo' => '9509','cliente' => 'AC MOZARLANDIA - GO'],
            ['mcu_cliente' => '57145','codigo' => '9510','cliente' => 'AC ARAGUAIA SHOPPING - GO'],
            ['mcu_cliente' => '6763','codigo' => '9511','cliente' => 'AC NOVA CRIXAS - GO'],
            ['mcu_cliente' => '6771','codigo' => '9512','cliente' => 'AC LEOPOLDO DE BULHOES - GO'],
            ['mcu_cliente' => '6651','codigo' => '9513','cliente' => 'AC MUNDO NOVO - GO'],
            ['mcu_cliente' => '6645','codigo' => '9514','cliente' => 'AC ARUANÂ - GO'],
            ['mcu_cliente' => '46556','codigo' => '9515','cliente' => 'CDD RIO VERDE - GO'],
            ['mcu_cliente' => '6754','codigo' => '9516','cliente' => 'AC SERRANÓPOLIS - GO'],
            ['mcu_cliente' => '6941','codigo' => '9517','cliente' => 'AC PEROLANDIA - GO'],
            ['mcu_cliente' => '6828','codigo' => '9518','cliente' => 'AC ARENOPOLIS - GO'],
            ['mcu_cliente' => '6761','codigo' => '9519','cliente' => 'AC DAMOLANDIA - GO'],
            ['mcu_cliente' => '6857','codigo' => '9520','cliente' => 'AC CEZARINA - GO'],
            ['mcu_cliente' => '59077','codigo' => '9521','cliente' => 'AC PROMISSÃO - GO'],
            ['mcu_cliente' => '47864','codigo' => '9522','cliente' => 'AC BONOPOLIS - GO'],
            ['mcu_cliente' => '46556','codigo' => '9523','cliente' => 'AC RIO VERDE - ENTREPOSTO - GO'],
            ['mcu_cliente' => '434244','codigo' => '9556','cliente' => 'ARQUIVO GERAL - GO'],



        ]);
        $this->command->info('Clientes de Monitoramento importados com sucesso!');
    }
}
